name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        pip3 install trufflehog --user
        pwd
        ls -la
        id
        export PATH=$PATH:~/.local/bin
        trufflehog
        echo ${PWD}
        export TRUFFLEHOG=`trufflehog file://${PWD}/ -x trufflehog-excludes.txt`
        echo $TRUFFLEHOG
        if [[ -z $TRUFFLEHOG ]]; then exit 0; fi
        exit 1;
    - name: Slack notification
      if: failure()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      uses: Ilshidur/action-slack@master
      with:
        args: 'Potential Secrets found in: WIP'
        
